export class AddressValidate {
    /** indicates whether the address is valid. If it is not, this is the only property returned. */
    isValid!: boolean;

    /** the address validated */
    address!: string;

    /** the hex encoded scriptPubKey generated by the address */
    scriptPubKey!: string;

    /** indicates whether the address is yours */
    ismine!: boolean;

    /** whether the key is a script */
    isscript!: boolean;

    /** the hex value of the raw public key */
    pubkey!: string;

    /** whether the address is compressed */
    iscompressed!: boolean;

    /** DEPRECATED the account associated with the address; "" is the default account */
    account!: string;
}